### ISSUE TITLE
Failed as still has NSOSStatusErrorDomain:-67701 error with Jamf enrollment

### ISSUE THREAD

**Issue by bkdgmx** [zackn9ne/make_jamf_vm#2]
Not sure if it's because the macOS 10.15.x is a linked clone

**********************************************************

*** Shutdown your VM's and Quit VMWARE ***
Press enter to continue.
fake Serial Number Generated and ready to use
*** We are about to pop up your finder window of the default VMWare VM's location so you can do this easier
**** Drag the VMX file to the whitespace here and press [enter] when done ****
/Users/Shared/Virtual\ Machines/macOS\ 10.15.x.vmwarevm 
Your getting ModelIdentifier MacBookPro15,1 is this OK? [y/N] y
Do you want fake Serial Number or your own [y/N] y
sed: /Users/Shared/Virtual Machines/macOS 10.15.x.vmwarevm: in-place editing only works for regular files
sed: /Users/Shared/Virtual Machines/macOS 10.15.x.vmwarevm: in-place editing only works for regular files
sed: /Users/Shared/Virtual Machines/macOS 10.15.x.vmwarevm: in-place editing only works for regular files
sed: /Users/Shared/Virtual Machines/macOS 10.15.x.vmwarevm: in-place editing only works for regular files
sed: /Users/Shared/Virtual Machines/macOS 10.15.x.vmwarevm: in-place editing only works for regular files
sed: /Users/Shared/Virtual Machines/macOS 10.15.x.vmwarevm: in-place editing only works for regular files
sed: /Users/Shared/Virtual Machines/macOS 10.15.x.vmwarevm: in-place editing only works for regular files
make_jamf_vm.sh: line 47: /Users/Shared/Virtual Machines/macOS 10.15.x.vmwarevm: Is a directory
make_jamf_vm.sh: line 48: /Users/Shared/Virtual Machines/macOS 10.15.x.vmwarevm: Is a directory
*** Welcome to your new Mac ***
*******************************
*******************************
*******************************
*******************************
*** MacBookPro15,1 ************
*** VMxxxxxxxxxx *************
*******************************
*******************************

**Comment by bkdgmx** [comment]
Ran the script again on the actual VM, not the linked clone. Still the same output and result. Although it says welcome to your new mac with the new serial number, the VM's serial number was not changed.

**Comment by zackn9ne** [comment]
I just realize GIF is actually wrong. You have to "Show package contents on the VM", find the ".vmx" file inside and drag that.

this implies you dragged the VM itself: "make_jamf_vm.sh: line 47: /Users/Shared/Virtual Machines/macOS 10.15.x.vmwarevm: Is a directory"

**Comment by zackn9ne** [comment]
@ccsben updated the GIF in the readme, made some textual changes to the menu prompts to make it more obvious, plus added a forcequit to VMWare in said prompts. enjoy!
